### PR TITLE
Increase grid theme max width to 13

### LINKED ISSUE #742: Support up to w13 (or w12) in Grid Theme
**Describe the bug**

While creating a matrix question, users are able to have a maximum column of 10 but when they try to have more then 10 columns the matrix question gets visually distorted.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).
1. Upload this xlsform with `w10` and test it with KoBoToolbox. 
[matrix_Working.xlsx](https://github.com/enketo/enketo-express/files/5169827/matrix_Working.xlsx)
It has `10 columns` for a matrix question and does not have any visualization issue. As a reference please see the image as shown below:
Image 1

2. Now upload this xlsform with `w11` and test it with KoBoToolbox.
[matrix_Error.xlsx](https://github.com/enketo/enketo-express/files/5169838/matrix_Error.xlsx)
It has `11 columns` for a matrix question and the table gets distorted. As a reference please see the image as shown below:
Image 2

**Expected behavior**

Users are able to create a survey form for a matrix question with more than 10 columns without the tables being distorted.

**Browser and OS (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome]

**Additional context**

`Community Forum Link:` https://community.kobotoolbox.org/t/unable-to-include-14-columns-in-a-matrix-question/12037

### PR DESCRIPTION
**Pull request by joshuaberetta**
closes #742

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
Given the issue thread has screenshots of this in action, I haven't run it myself or tried to see whether there might be another place where a max is defined. Seems reasonable it'd just be this one!

**Comment by joshuaberetta** [comment]
Yes — that's the only place I could find that needed to be updated.

**Comment by joshuaberetta** [comment]
@lognaturel, who is responsible for merging this change? Should I include @MartijnR as a reviewer for small fixes?

**Comment by lognaturel** [comment]
I currently prefer letting @MartijnR take a look and do merges the way he likes as we do more transfer of knowledge and process. For something this narrow, it doesn't matter when it gets merged because it won't lead to conflicts. So I'd just leave it open and approved until we coordinate on the next `enketo-core` release.

**Comment by joshuaberetta** [comment]
Ok good to know 👍

**Comment by MartijnR** [comment]
Thanks!

**Pull request merged**
