### PR TITLE
Update Form-model.js

### PR DESCRIPTION
**Pull request by theywa**
adoptNode is not supported on IE 11 so need alternative function to prevent error and allow saved value show up on edit form

### CODE REVIEW

**Comment by MartijnR** [comment]
Thanks! Are you sure that fixes the IE problems with loading an existing instance? I thought I tried this.

If it does: 

That is great! 👍 Would it work to check for the feature instead of the useragent? =>

```if (typeof this.xml.adoptNode === 'function')```

Running `grunt jsbeautifier:fix` should fix the code style issues.

**Comment by MartijnR** [comment]
Isn't importNode supposed to be supported in IE11? In other words, do we need the polyfill?. Note, that we do not need (or even want) support for older versions of IE due to so many other problems.

**Comment by theywa** [comment]
if your question "Are you sure that fixes the IE problems with loading an existing instance?" refer to issue on IE 11 edit form there will be no saved value show up ? If yes then yes it solved that issue.
Using "adoptNode" will result error "No such interface supported" also using "if (typeof this.xml.adoptNode === 'function')" will create that issue too.. 
here some demo http://supadosworks.com/videos/demo-issue/OC-7124/OC-7124-fix-show-value-on-edit.ogv.
Some article say importNode and adoptNode not supported in IE but I'm not sure if it including IE11,. Not tested on older version IE yet and I also don't know if we need polyfill or not.

**Comment by MartijnR** [comment]
Thanks!

Nice of Microsoft... So document.adoptNode is a function, it just doesn't work...

Document.importNode is also a function. If you can check whether that one actually works in IE11 without the polyfill, that would be great.

screen shot 2016-05-25 at 8 01 29 am

**Comment by theywa** [comment]
I tried that, but like adoptNode, document.importNode and this.xml.importNode also generate same error on IE. It's look like that polyfill needed at least until we found better solution,.

**Comment by MartijnR** [comment]
Oh man... I can't wait for IE11 to die... (and then Safari).

Will test and then merge!

**Comment by MartijnR** [comment]
👍  I just had to change a few remaining code style and jshint issues, so I added them, squashed, and merged.

Thanks!

Next time, it would be great if you could try to make `npm test` pass.

**Pull request closed without merging**
