### PR TITLE
Insert required enketo-transformer version number at build-time

### LINKED ISSUE #415: Move Form.getRequiredTransformerVersion to a separate module?
It's a shame that `getRequiredTransformerVersion()` is implemented in `Form.js`, as it means enketo-core's `package.json` file is included when we browserify our code, even though this function isn't used.

If this function could be moved to its own module, then it, and `package.json`, would only be included when needed.

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #415

### CODE REVIEW

**Comment by MartijnR** [comment]
This is cool stuff! Thanks! I learned something new.

My only concern is that it requires updating all build systems of apps that use Enketo Core. The regular `require('enketo-core')` will now have a broken `getRequiredTransformerVersion()` function.

**Comment by alxndrsn** [comment]
Yes, it's true!  This `replace` step would also need to be implemented in downstream projects.

Some alternatives I can think of:

* keep the version number updated manually in `Form.js`
* write a similar `rewrite` Grunt task for inserting the version number into `Form.js`, and run this at appropriate times (e.g. by adding an [`npm prepublishOnly` step to `package.json`'s `scripts` section](https://docs.npmjs.com/misc/scripts)?)

**Comment by MartijnR** [comment]
Let's do your:

> keep the version number updated manually in Form.js

and add a test that would immediately show in Travis when we forget to update.

**Comment by alxndrsn** [comment]
Neat - I hadn't thought of writing a test for it(!)  Great idea :¬)

**Comment by alxndrsn** [comment]
Updated to hard-code the expected value in `Form.js`, and test for this in `form.spec.js`.

This PR will need to be squashed when merged.

Example test failure:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) required enketo-transformer version can be obtained FAILED
	Expected '1.15.1' to be '1.15.2', 'It looks like enketo-transformer has been updated in package.json from 1.15.1 to 1.15.2.  You also need to update the value returned by From.getRequiredTransformerVersion() to the new version number.'.
```

**Pull request merged**
