### PR TITLE
Fix: ensure evaluation cascade additions receive form context and update arguments

### PR DESCRIPTION
**Pull request by eyelidlessness**
This is a slight variation on #893. The rationale for the difference is [explained here](https://github.com/enketo/enketo-core/pull/893#issuecomment-1132075839).

### CODE REVIEW

**Review by MartijnR — APPROVED** [review]
That's great. Thanks!

**Comment by lognaturel** [comment]
@MartijnR we have recently been leaving a few weeks between releases unless there’s something urgently needed. In general, do let us know if there’s urgency. I imagine this is a critical regression for those who depend on it.

**Comment by MartijnR** [comment]
Thanks @lognaturel. This is particular one would be nice to get released in enketo-core because of the stage in OpenClinica's deployment. However, it would not be a big problem to just point to the commit in OpenClinica's fork. In that case, it would be great to just get it merged into master.

**Comment by lognaturel** [comment]
@MartijnR You can still merge, right?? If you're reviewing, you should certainly feel free to take that last step. I can't do it right this moment but let's try to release today.

**Comment by MartijnR** [comment]
> @MartijnR You can still merge, right??

I'm going to try! :D

Thank you!

**Pull request merged**
