### PR TITLE
Remove no-op assignments from widgets

### PR DESCRIPTION
**Pull request by alxndrsn**
Looks like `data` is not used again after it was reassigned.

### CODE REVIEW

**Comment by MartijnR** [comment]
Yes, looks like you're right! Is the case in all widgets it seems. Do you want to add the others too perhaps (or should I get off my lazy ass and do this - you can tell me)?

**Comment by alxndrsn** [comment]
I'll take a look :)

**Comment by alxndrsn** [comment]
Updated.

**Comment by MartijnR** [comment]
Thanks!

**Pull request merged**
