### PR TITLE
Make `FormModel.types` accessible publicly

### PR DESCRIPTION
**Pull request by alxndrsn**
This allows widgets or other extensions to add validation for custom data types.

Issue: #311

### CODE REVIEW

**Comment by MartijnR** [comment]
Of course! I like it! I may want re-arrange code, but will look later.

**Comment by alxndrsn** [comment]
:+1:

**Comment by MartijnR** [comment]
Alex if this becomes a prototype property, it will still work for you, right?

**Comment by alxndrsn** [comment]
Would I just change this line:
https://github.com/alxndrsn/medic-webapp/blob/901e858912365962a0a5f419a627826908b6cd65/static/js/enketo/widgets/phone-widget.js#L19
to read
```javascript
FormModel.prototype.types.phone = ...
```
or would I need to apply the type changes to each instance of `FormModel` via e.g. `myForm.getModel().types`?

**Comment by MartijnR** [comment]
Yes, I think so too. This should better as you won't have to changes the instances. I'll merge this now.

**Comment by alxndrsn** [comment]
Great, thanks!

**Comment by MartijnR** [comment]
thank you

**Pull request closed without merging**
