### PR TITLE
Add Issue template and Pull request template so this repository more contribution friendly

### PR DESCRIPTION
**Pull request by pamungkaski**
### Proposed changes in this pull request

- Add Issue template and Pull request template in .github/ so this repository more contribution friendly

### When should this PR be merged

- AnyTime

### Risks

- None

### Follow-up actions

- None

### CODE REVIEW

**Comment by alxndrsn** [comment]
Hi @pamungkaski, @MartijnR can comment on whether this PR is helpful.  As an aside, it looks like you've included one of your IDEA project files (`enketo-core.iml`) with this pull request.  Also, instead of making changes to individual projects' `.gitignore` file, you might want to set up a global gitignore for these kinds of files, and `.DS_Store`: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by pamungkaski** [comment]
@alxndran thanks for your response
Going to do that, thanks for the advice

**Comment by MartijnR** [comment]
@pamungkaski Thanks for your PR. 

I'm trying to figure out if this will increase collaboration or create an additional hurdle though. I personally don't like these templates that much when I contribute to an open source project (but that could just be me). E.g. I wonder whether it discourage asking questions or suggesting features or anything that doesn't fit the template. I think their role is more a tool to deal with problems by unclear PRs and an unmanageable avalanche of Issues. 

Could you elaborate on why this could improve contribution-friendliness?

**Comment by pamungkaski** [comment]
@MartijnR hi, thanks for your response
Actually for the Issue template it just for bug reporting so the community could help to look out for bug if you are too busy for little bug , and then the other can send PR to resolve the bug too because of the issue template will make it clear how to reproduce the bug and help the investigation.
For the enchantment and feature suggestion i need to work on the template still.
For the PR template it make you easier to understand what they propose on their PR and make the community more critical when resolving bug.
Yeah actually the purpose is to make the issue more clear for new contributor to read it.

Hope you have a nice weekend

**Comment by alxndrsn** [comment]
I'm not in favour of these templates as there doesn't seem to be a big problem with this project and unclear issue reports or pull requests.

That aside, there are still unrelated files included in this PR.

Either way, if it's not going to get merged can we close the PR?

**Comment by MartijnR** [comment]
Thanks. Yes, let's not merge and revisit if there is ever a need or templates become more flexible.

**Pull request closed without merging**
