### PR TITLE
jr:choice-name regex improvement & test

### PR DESCRIPTION
**Pull request by alxndrsn**

### CODE REVIEW

**Comment by alxndrsn** [comment]
@MartijnR let me know what you think of this, and any comments on the code style.  If the approach is fine I'll get it cleaned up and squash the commits for merge.

**Comment by MartijnR** [comment]
PS. I didn't merge because you mentioned you wanted to clean it up first (though it's fine with me already). Let me know if you want to see this merged already!

**Comment by alxndrsn** [comment]
Not sure what the clean-up plan was, so please merge!

**Comment by MartijnR** [comment]
merged by 656a20ede4db431e1f9aa3ea9c46ae3729911c33. Thanks!

**Pull request closed without merging**
