### PR TITLE
1a test coverage measure

### LINKED ISSUE #571: Measure testing code coverage
After adding this to master, we should create a branch off the last release before 5.0.0-alpha0  (i.e. `4.60.6`) and run the coverage analysis on that code. That is our baseline that we should report on to the donor.

As part of the 5.0.0 release, the widgets were converted and many tests were added (generic widget tests that almost all widgets should pass). This work will have improved code coverage.

### PR DESCRIPTION
**Pull request by magicznyleszek**
This adds:

1. coverage percentages display in command line (when you run `npm run test`)
2. coverage report in `./test-coverage` that you can display in your browser
3. README.md coverage badge auto-generation

Closes #571

### CODE REVIEW

**Comment by magicznyleszek** [comment]
@MartijnR I excluded these libraries and coverage jumped by 10%! :)

**Comment by magicznyleszek** [comment]
You can check the `pre-dial-coverage` branch now :)

pre-DIAL:

```
=============================== Coverage summary ===============================
Statements   : 58.63% ( 3468/5915 )
Branches     : 49.82% ( 1659/3330 )
Functions    : 51.5% ( 514/998 )
Lines        : 58.63% ( 3467/5913 )
================================================================================
```

Current:

```
=============================== Coverage summary ===============================
Statements   : 70.65% ( 2918/4130 )
Branches     : 62.85% ( 1499/2385 )
Functions    : 66.13% ( 531/803 )
Lines        : 70.78% ( 2892/4086 )
================================================================================

```

**Comment by MartijnR** [comment]
Nice! Not bad to get a 10% increase without a targeted effort (and 70% is a pretty cool number!). Yes, I think the conversion to ES6 may be the main cause of the lines decrease, as well as the widget architecture changes that removed duplication.

**Comment by MartijnR** [comment]
hi @magicznyleszek, 

I've been trying to run pre-dial-coverage, but it doesn't run. Just wanted to check if there is perhaps a commit you haven't pushed to that branch yet.

**Comment by magicznyleszek** [comment]
@MartijnR all the commits are pushed. 

Firstly I tried running it again after switching from `master` and indeed it didn't work - I had this error:

```
16 08 2019 23:43:48.865:ERROR [framework.browserify]: bundle error
16 08 2019 23:43:48.868:ERROR [framework.browserify]: 
/Users/leszek/Sites/enketo/enketo-core/test/mock/forms.js:1
export default {
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Then I wanted to test it from fresh start and it worked OK:

1. cloned a fresh repo copy
2. changed branch to `pre-dial-coverage`
3. switched node to 8.15.1 (with nvm)
4. `npm install`
5. `npm run test`

So I suspect that some leftovers from `master` branch or a newer version of Node is causing the problems? Please try again from a fresh start and if it doesn't work we will try debugging it further :)

**Pull request merged**
